create table monitored_api
(
    id                  bigint generated by default as identity primary key,
    name                varchar(255)             not null,
    application         varchar(255)             not null,
    team                varchar(255)             not null,
    environment         varchar(32)              not null,
    swagger_url         varchar(2048)            not null,
    description         varchar(4000),
    polling_enabled     boolean                  not null default true,
    current_contract_id bigint,
    created_at          timestamp with time zone not null,
    updated_at          timestamp with time zone not null
);
create table api_contract
(
    id                  bigint generated by default as identity primary key,
    api_id              bigint                   not null references monitored_api (id) on delete cascade,
    version             varchar(100)             not null,
    hash                varchar(64)              not null,
    raw_document        text                     not null,
    normalized_document text                     not null,
    detected_at         timestamp with time zone not null
);
alter table monitored_api
    add constraint fk_current_contract foreign key (current_contract_id) references api_contract (id);
create table consumer_mapping
(
    id                   bigint generated by default as identity primary key,
    consumer_application varchar(255)             not null,
    consumer_method      varchar(16)              not null,
    consumer_path        varchar(1024)            not null,
    consumer_field_path  varchar(1024)            not null,
    producer_api_id      bigint                   not null references monitored_api (id) on delete cascade,
    producer_method      varchar(16)              not null,
    producer_path        varchar(1024)            not null,
    producer_field_path  varchar(1024)            not null,
    transformation       varchar(255),
    required             boolean                  not null default false,
    created_at           timestamp with time zone not null,
    updated_at           timestamp with time zone not null
);
create table contract_change
(
    id              bigint generated by default as identity primary key,
    old_contract_id bigint references api_contract (id),
    new_contract_id bigint                   not null references api_contract (id),
    change_type     varchar(64)              not null,
    severity        varchar(32)              not null,
    endpoint        varchar(1024),
    json_path       varchar(1024),
    old_value       text,
    new_value       text,
    confidence      integer                  not null,
    detected_at     timestamp with time zone not null
);
create table impact
(
    id                 bigint generated by default as identity primary key,
    contract_change_id bigint                   not null references contract_change (id) on delete cascade,
    mapping_id         bigint                   not null references consumer_mapping (id) on delete cascade,
    impact_level       varchar(32)              not null,
    risk_score         integer                  not null,
    reason             varchar(4000)            not null,
    status             varchar(32)              not null,
    detected_at        timestamp with time zone not null
);