package com.example.contractguardian.persistance.entity;

public enum ChangeType {ENDPOINT_ADDED, ENDPOINT_REMOVED, RESPONSE_FIELD_ADDED, RESPONSE_FIELD_REMOVED, FIELD_TYPE_CHANGED, REQUIRED_TO_OPTIONAL, OPTIONAL_TO_REQUIRED, NULLABLE_CHANGED, ENUM_CHANGED, FIELD_MOVED, LIKELY_FIELD_RENAME}